### ISSUE TITLE
[Bug] `<SeoKit siteName="Something" />` does not work

### ISSUE THREAD

**Issue by madebyfabian** [harlan-zw/nuxt-seo-kit#25] opened 2023-02-06 06:33 UTC
### Describe the bug

Followup on:
https://github.com/harlan-zw/nuxt-seo-kit/issues/20

I tried to do

```html
<template>
	<div>
		<SeoKit siteName="Override in app.vue!" />
		<NuxtPage />
	</div>
</template>
```

But the override never gets accepted.
![Bildschirm­foto 2023-02-06 um 07 31 41](https://user-images.githubusercontent.com/32813692/216899433-b0976c45-6980-4837-ab2c-908aa4801278.jpg)

It's still using the `siteName` from `nuxt.config.ts`

Check the reprod repo branch for a minimal example.

https://github.com/madebyfabian/nuxt3-generated-reprod/pull/4/files

Live:
https://nuxt3-generated-reprod-git-with-nuxt-seo-kit-madebyfabian.vercel.app/

### Reproduction

https://github.com/madebyfabian/nuxt3-generated-reprod/pull/4/files

### System Info

```Shell
- Operating System: `Darwin`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.1`
- Package Manager:  `pnpm@7.26.3`
- Builder:          `vite`
- User Config:      `extends`, `runtimeConfig`, `app`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment] 2023-02-09 09:48
The issue is that you can't modify runtime config within the app and the title template uses runtime config. I'll see about adding a new feature to nuxt-unhead, support for arbitrary template vars

**Comment by harlan-zw** [comment] 2023-02-25 04:53
@madebyfabian 

This should be fixed in the Unhead v1.1 update, you can try Nuxt SEO Kit 1.3 but you may need to wait for it to land in Nuxt officially.

**Comment by madebyfabian** [comment] 2023-02-25 05:10
Sounds great, thank you! Will try it.

**Comment by madebyfabian** [comment] 2023-02-25 08:18
@harlan-zw Just for my understanding, I can try out the features right now when upgrading to 
```json
"nuxt": "^3.2.2",
"nuxt-seo-kit": "^1.3.0"
```
right? Done it and get several issues.

**Comment by harlan-zw** [comment] 2024-01-04 16:05
This is solved in v2, see the docs here: https://nuxtseo.com/site-config/guides/runtime-site-config

**Closed by harlan-zw** 2024-01-04 16:05 UTC
