### ISSUE TITLE
Page title not change when go to other page 

### ISSUE THREAD

**Issue by nasirDoe** [harlan-zw/nuxt-seo-kit#90] opened 2023-08-31 04:31 UTC
### Describe the bug

When i updated nuxt version to 3.7 and nuxt-seo-kit  version to 1.3.10, i got a problem with page title not change after go to other page via navigation. but i try to reloading the page, the title is changed to the current page title. 

The stackblitz links:
[https://stackblitz.com/edit/nuxt-starter-dcpm9o](url)

### Reproduction

https://nuxtstarterdcpm9o-h44w--3000--33975f1d.local-credentialless.webcontainer.io/

### System / Nuxt Info

```Shell
OSX 13 Ventura
Nuxt 3.7
Browser Chrome (Brave)
```

**Comment by harlan-zw** [comment] 2023-09-05 09:15
Hey @nasirDoe, thanks for the issue and reproduction!

Looks like this is fixed with the latest version of Unhead, see https://stackblitz.com/edit/nuxt-starter-dcpm9o?file=README.md

You'll need to delete your lock file + node_modules and re-install to use the latest.

**Closed by harlan-zw** 2023-09-05 09:15 UTC

**Comment by nasirDoe** [comment] 2023-09-06 13:20
Ok thankyou sir
